-- SUPABASE SCHEMA FOR IRONLINE GARAGE SPA
-- Run this in Supabase SQL Editor, then create an admin user under
-- Authentication > Users.

create table if not exists garage_settings (
  id bigint generated by default as identity primary key,
  garage_name text not null,
  owner_name text not null,
  location text not null,
  map_link text,
  phone text not null,
  email text not null,
  open_time time not null,
  close_time time not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists live_feed (
  id bigint generated by default as identity primary key,
  vehicle_name text not null,
  description text not null,
  status text not null check (status in ('IN QUEUE','IN PAINT BOOTH','IN REPAIR','COMPLETED')),
  media_url text,
  created_at timestamptz default now()
);

create table if not exists portfolio (
  id bigint generated by default as identity primary key,
  title text not null,
  media_url text not null,
  created_at timestamptz default now()
);

alter table garage_settings enable row level security;
alter table live_feed enable row level security;
alter table portfolio enable row level security;

-- PUBLIC CUSTOMER READ
create policy "public read garage settings" on garage_settings for select using (true);
create policy "public read live feed" on live_feed for select using (true);
create policy "public read portfolio" on portfolio for select using (true);

-- AUTHENTICATED ADMIN WRITE
create policy "admins insert settings" on garage_settings for insert to authenticated with check (true);
create policy "admins update settings" on garage_settings for update to authenticated using (true) with check (true);
create policy "admins insert feed" on live_feed for insert to authenticated with check (true);
create policy "admins delete feed" on live_feed for delete to authenticated using (true);
create policy "admins insert portfolio" on portfolio for insert to authenticated with check (true);
create policy "admins delete portfolio" on portfolio for delete to authenticated using (true);

-- Optional: seed one profile row
insert into garage_settings (garage_name, owner_name, location, map_link, phone, email, open_time, close_time)
select 'Star painting works', 'Mujammil jamadar', 'Rabkavi- Banahatti road, Infront of SDM Trust''s Danigond College of Commerce, Terdal', 'https://www.google.com/maps/search/?api=1&query=F3R6%2B2PM%20SDM%20Trust%27s%20Danigond%20College%20of%20Commerce%20(PU%20%26%20B.com)%2C%20Terdal%2C%20Terdal%20Rural%2C%20Karnataka%20587315', '+918867442645', 'jamadarmujammil9@gmail.com', '09:00', '20:00'
where not exists (select 1 from garage_settings);
